### ISSUE TITLE
Bug: Ao cadastrar Admin, a conta é cadastrada e invalidada

### ISSUE THREAD

**Issue by marcioonodera** [bndes/rbb-identificacao#9]
O processo de automatização da verificação do arquivo (mockado) está dando erro, e a conta está recebendo o status Invalida.

Segue mensagem do Back abaixo.

Sistema está gravando arquivo na pasta

}
ConnectionError: Failed to connect to d-1-qsa:1433 - getaddrinfo ENOTFOUND d-1-qsa
    at Connection.<anonymous> (N:\Git\rbb-identificacao\Back\node_modules\mssql\lib\tedious.js:244:17)
    at Object.onceWrapper (events.js:422:26)
    at Connection.emit (events.js:315:20)
    at Connection.socketError (N:\Git\rbb-identificacao\Back\node_modules\tedious\lib\connection.js:1095:12)
    at N:\Git\rbb-identificacao\Back\node_modules\tedious\lib\connection.js:961:21
    at GetAddrInfoReqWrap.callback (N:\Git\rbb-identificacao\Back\node_modules\tedious\lib\connector.js:48:16)
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (dns.js:75:17) {
  code: 'ESOCKET',
  originalError: ConnectionError: Failed to connect to d-1-qsa:1433 - getaddrinfo ENOTFOUND d-1-qsa
      at ConnectionError (N:\Git\rbb-identificacao\Back\node_modules\tedious\lib\errors.js:13:12)
      at Connection.socketError (N:\Git\rbb-identificacao\Back\node_modules\tedious\lib\connection.js:1095:28)
      at N:\Git\rbb-identificacao\Back\node_modules\tedious\lib\connection.js:961:21
      at GetAddrInfoReqWrap.callback (N:\Git\rbb-identificacao\Back\node_modules\tedious\lib\connector.js:48:16)
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (dns.js:75:17) {
    code: 'ESOCKET'
  }
}
ConnectionError: Failed to connect to d-1-qsa:1433 - getaddrinfo ENOTFOUND d-1-qsa
    at Connection.<anonymous> (N:\Git\rbb-identificacao\Back\node_modules\mssql\lib\tedious.js:244:17)
    at Object.onceWrapper (events.js:422:26)
    at Connection.emit (events.js:315:20)
    at Connection.socketError (N:\Git\rbb-identificacao\Back\node_modules\tedious\lib\connection.js:1095:12)
    at N:\Git\rbb-identificacao\Back\node_modules\tedious\lib\connection.js:961:21
    at GetAddrInfoReqWrap.callback (N:\Git\rbb-identificacao\Back\node_modules\tedious\lib\connector.js:48:16)
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (dns.js:75:17) {
  code: 'ESOCKET',
  originalError: ConnectionError: Failed to connect to d-1-qsa:1433 - getaddrinfo ENOTFOUND d-1-qsa
      at ConnectionError (N:\Git\rbb-identificacao\Back\node_modules\tedious\lib\errors.js:13:12)
      at Connection.socketError (N:\Git\rbb-identificacao\Back\node_modules\tedious\lib\connection.js:1095:28)
      at N:\Git\rbb-identificacao\Back\node_modules\tedious\lib\connection.js:961:21
      at GetAddrInfoReqWrap.callback (N:\Git\rbb-identificacao\Back\node_modules\tedious\lib\connector.js:48:16)
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (dns.js:75:17) {
    code: 'ESOCKET'
  }
}
0xc34Af5C906A80Dda6761740e3CB5465bb357597b
BigNumber { _hex: '0x03' }
BigNumber { _hex: '0x1e03733b4825' }
b24530b063d5a53311e5210d3f42a1fba0ad91fa69c2f5744201817253d40a99
BigNumber { _hex: '0x621e6e58' }
buscaTipoArquivo
targetPathToCalculateHash
arquivos/declaracao/DECL_33000167000101_0_0xc34Af5C906A80Dda6761740e3CB5465bb357597b_b24530b063d5a53311e5210d3f42a1fba0ad91fa69c2f5744201817253d40a99.PDF
** ORACLE ** - Nao conseguiu encontrar o arquivo da declaracao.
** ORACLE ** - Faz chamada da invalidação do registro.
0x56e71ed3f708aecaa8cdb8c82e019be48748c4ca2e85e8d6e403b1d556ccefbd
** ORACLE ** - O cadastro foi invalidado.
ConnectionError: Failed to connect to d-1-qsa:1433 - getaddrinfo ENOTFOUND d-1-qsa
    at Connection.<anonymous> (N:\Git\rbb-identificacao\Back\node_modules\mssql\lib\tedious.js:244:17)
    at Object.onceWrapper (events.js:422:26)
    at Connection.emit (events.js:315:20)
    at Connection.socketError (N:\Git\rbb-identificacao\Back\node_modules\tedious\lib\connection.js:1095:12)
    at N:\Git\rbb-identificacao\Back\node_modules\tedious\lib\connection.js:961:21
    at GetAddrInfoReqWrap.callback (N:\Git\rbb-identificacao\Back\node_modules\tedious\lib\connector.js:48:16)
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (dns.js:75:17) {
  code: 'ESOCKET',
  originalError: ConnectionError: Failed to connect to d-1-qsa:1433 - getaddrinfo ENOTFOUND d-1-qsa
      at ConnectionError (N:\Git\rbb-identificacao\Back\node_modules\tedious\lib\errors.js:13:12)
      at Connection.socketError (N:\Git\rbb-identificacao\Back\node_modules\tedious\lib\connection.js:1095:28)
      at N:\Git\rbb-identificacao\Back\node_modules\tedious\lib\connection.js:961:21
      at GetAddrInfoReqWrap.callback (N:\Git\rbb-identificacao\Back\node_modules\tedious\lib\connector.js:48:16)
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (dns.js:75:17) {
    code: 'ESOCKET'
  }
}

**Comment by marcioonodera** [comment]
Atualização: criei a pasta \arquivos\declaracao na mão, e quando cadastrei o CNPJ, ele validou a conta automaticamente dessa vez. e gravou a declaração com o nome novo (CNPJ + Address + Hash,pdf) na pasta, como esperado.

![image](https://user-images.githubusercontent.com/42449573/109863442-65a51180-7c40-11eb-8f0c-2c04b5dc2eeb.png)
